// Comprehensive 91-item learning curriculum (56 lessons + 35 games)
import type { LearningItem, GameConfig, LessonConfig } from '@/types/comprehensive-learning';

export const COMPREHENSIVE_LEARNING_ITEMS: LearningItem[] = [
  // Unit 1: Foundation (10 lessons + 6 games)
  {
    id: 'lesson-1',
    type: 'lesson',
    number: 1,
    title: 'Introduction to English Language',
    titleAr: 'مقدمة في اللغة الإنجليزية',
    description: 'Learn the basics of English language structure and sounds',
    descriptionAr: 'تعلم أساسيات بنية اللغة الإنجليزية والأصوات',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: [],
    estimatedTime: 15,
    unlocked: true,
    completed: false
  },
  {
    id: 'game-1',
    type: 'game',
    number: 2,
    title: 'Alphabet Adventure',
    titleAr: 'مغامرة الأبجدية',
    description: 'Interactive game to master English alphabet',
    descriptionAr: 'لعبة تفاعلية لإتقان الأبجدية الإنجليزية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-1'],
    estimatedTime: 10,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-2',
    type: 'lesson',
    number: 3,
    title: 'English Alphabet',
    titleAr: 'الأبجدية الإنجليزية',
    description: 'Master all 26 letters with pronunciation',
    descriptionAr: 'إتقان جميع الـ26 حرفاً مع النطق',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['game-1'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-3',
    type: 'lesson',
    number: 4,
    title: 'English Numbers',
    titleAr: 'الأرقام الإنجليزية',
    description: 'Learn numbers 1-100 with pronunciation',
    descriptionAr: 'تعلم الأرقام من 1-100 مع النطق',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-2'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-2',
    type: 'game',
    number: 5,
    title: 'Number Matching Challenge',
    titleAr: 'تحدي مطابقة الأرقام',
    description: 'Match written numbers with spoken numbers',
    descriptionAr: 'طابق الأرقام المكتوبة مع الأرقام المنطوقة',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-3'],
    estimatedTime: 12,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-4',
    type: 'lesson',
    number: 6,
    title: 'Basic Colors',
    titleAr: 'الألوان الأساسية',
    description: 'Learn essential colors in English',
    descriptionAr: 'تعلم الألوان الأساسية باللغة الإنجليزية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['game-2'],
    estimatedTime: 15,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-3',
    type: 'game',
    number: 7,
    title: 'Color Quest',
    titleAr: 'مهمة الألوان',
    description: 'Visual color identification game',
    descriptionAr: 'لعبة تحديد الألوان البصرية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-4'],
    estimatedTime: 8,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-5',
    type: 'lesson',
    number: 8,
    title: 'Greetings and Basic Words',
    titleAr: 'التحيات والكلمات الأساسية',
    description: 'Essential greetings and everyday words',
    descriptionAr: 'التحيات الأساسية والكلمات اليومية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['game-3'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-4',
    type: 'game',
    number: 9,
    title: 'Greeting Simulator',
    titleAr: 'محاكي التحيات',
    description: 'Practice greetings in different situations',
    descriptionAr: 'تدرب على التحيات في مواقف مختلفة',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-5'],
    estimatedTime: 15,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-6',
    type: 'lesson',
    number: 10,
    title: 'Personal Pronouns',
    titleAr: 'الضمائر الشخصية',
    description: 'Master I, you, he, she, it, we, they',
    descriptionAr: 'إتقان أنا، أنت، هو، هي، هو/هي، نحن، هم',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['game-4'],
    estimatedTime: 22,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-7',
    type: 'lesson',
    number: 11,
    title: 'Present Simple Tense',
    titleAr: 'المضارع البسيط',
    description: 'Learn basic present tense structure',
    descriptionAr: 'تعلم بنية المضارع البسيط',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-6'],
    estimatedTime: 25,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-5',
    type: 'game',
    number: 12,
    title: 'Grammar Adventure: Present Simple',
    titleAr: 'مغامرة القواعد: المضارع البسيط',
    description: 'Story-based grammar practice',
    descriptionAr: 'تدريب القواعد المبني على القصص',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-7'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-8',
    type: 'lesson',
    number: 13,
    title: 'Articles (a, an, the)',
    titleAr: 'أدوات التعريف والتنكير',
    description: 'Master English articles usage',
    descriptionAr: 'إتقان استخدام أدوات التعريف الإنجليزية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['game-5'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-9',
    type: 'lesson',
    number: 14,
    title: 'Common Adjectives',
    titleAr: 'الصفات الشائعة',
    description: 'Essential descriptive words',
    descriptionAr: 'الكلمات الوصفية الأساسية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-8'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-10',
    type: 'lesson',
    number: 15,
    title: 'Family Members',
    titleAr: 'أفراد العائلة',
    description: 'Vocabulary for family relationships',
    descriptionAr: 'مفردات العلاقات العائلية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-9'],
    estimatedTime: 16,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-6',
    type: 'game',
    number: 16,
    title: 'Family Tree Builder',
    titleAr: 'بناء شجرة العائلة',
    description: 'Interactive family vocabulary game',
    descriptionAr: 'لعبة مفردات العائلة التفاعلية',
    difficulty: 'beginner',
    category: 'Foundation',
    prerequisites: ['lesson-10'],
    estimatedTime: 14,
    unlocked: false,
    completed: false
  },

  // Unit 2: Building Vocabulary (10 lessons + 6 games)
  {
    id: 'lesson-11',
    type: 'lesson',
    number: 17,
    title: 'Body Parts',
    titleAr: 'أجزاء الجسم',
    description: 'Learn vocabulary for body parts',
    descriptionAr: 'تعلم مفردات أجزاء الجسم',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['game-6'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-7',
    type: 'game',
    number: 18,
    title: 'Body Parts Puzzle',
    titleAr: 'لغز أجزاء الجسم',
    description: 'Interactive body parts identification',
    descriptionAr: 'تحديد أجزاء الجسم التفاعلي',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['lesson-11'],
    estimatedTime: 12,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-12',
    type: 'lesson',
    number: 19,
    title: 'Days and Months',
    titleAr: 'الأيام والشهور',
    description: 'Calendar vocabulary and usage',
    descriptionAr: 'مفردات التقويم والاستخدام',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['game-7'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-13',
    type: 'lesson',
    number: 20,
    title: 'Time Expressions',
    titleAr: 'تعبيرات الوقت',
    description: 'How to tell and express time',
    descriptionAr: 'كيفية قول الوقت والتعبير عنه',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['lesson-12'],
    estimatedTime: 22,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-8',
    type: 'game',
    number: 21,
    title: 'Time Master Challenge',
    titleAr: 'تحدي سيد الوقت',
    description: 'Practice telling time in English',
    descriptionAr: 'تدرب على قول الوقت بالإنجليزية',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['lesson-13'],
    estimatedTime: 15,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-14',
    type: 'lesson',
    number: 22,
    title: 'Weather and Seasons',
    titleAr: 'الطقس والفصول',
    description: 'Weather vocabulary and expressions',
    descriptionAr: 'مفردات الطقس والتعبيرات',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['game-8'],
    estimatedTime: 19,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-15',
    type: 'lesson',
    number: 23,
    title: 'Food and Drinks',
    titleAr: 'الطعام والشراب',
    description: 'Essential food vocabulary',
    descriptionAr: 'مفردات الطعام الأساسية',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['lesson-14'],
    estimatedTime: 21,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-9',
    type: 'game',
    number: 24,
    title: 'Restaurant Simulator',
    titleAr: 'محاكي المطعم',
    description: 'Order food in English simulation',
    descriptionAr: 'محاكاة طلب الطعام بالإنجليزية',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['lesson-15'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-16',
    type: 'lesson',
    number: 25,
    title: 'Shopping Vocabulary',
    titleAr: 'مفردات التسوق',
    description: 'Essential shopping expressions',
    descriptionAr: 'تعبيرات التسوق الأساسية',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['game-9'],
    estimatedTime: 17,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-17',
    type: 'lesson',
    number: 26,
    title: 'Transportation',
    titleAr: 'وسائل النقل',
    description: 'Vehicles and transportation vocabulary',
    descriptionAr: 'مفردات المركبات ووسائل النقل',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['lesson-16'],
    estimatedTime: 16,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-10',
    type: 'game',
    number: 27,
    title: 'Travel Adventure',
    titleAr: 'مغامرة السفر',
    description: 'Transportation vocabulary game',
    descriptionAr: 'لعبة مفردات وسائل النقل',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['lesson-17'],
    estimatedTime: 13,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-18',
    type: 'lesson',
    number: 28,
    title: 'Places and Directions',
    titleAr: 'الأماكن والاتجاهات',
    description: 'Location vocabulary and giving directions',
    descriptionAr: 'مفردات المواقع وإعطاء الاتجاهات',
    difficulty: 'beginner',
    category: 'Vocabulary',
    prerequisites: ['game-10'],
    estimatedTime: 23,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-19',
    type: 'lesson',
    number: 29,
    title: 'Past Simple Tense',
    titleAr: 'الماضي البسيط',
    description: 'Learn past tense formation and usage',
    descriptionAr: 'تعلم تكوين واستخدام الماضي',
    difficulty: 'intermediate',
    category: 'Grammar',
    prerequisites: ['lesson-18'],
    estimatedTime: 26,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-11',
    type: 'game',
    number: 30,
    title: 'Time Travel Grammar',
    titleAr: 'قواعد السفر عبر الزمن',
    description: 'Past tense adventure game',
    descriptionAr: 'لعبة مغامرة الماضي',
    difficulty: 'intermediate',
    category: 'Grammar',
    prerequisites: ['lesson-19'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-20',
    type: 'lesson',
    number: 31,
    title: 'Future Tense',
    titleAr: 'زمن المستقبل',
    description: 'Future expressions and planning',
    descriptionAr: 'تعبيرات المستقبل والتخطيط',
    difficulty: 'intermediate',
    category: 'Grammar',
    prerequisites: ['game-11'],
    estimatedTime: 24,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-12',
    type: 'game',
    number: 32,
    title: 'Future Planner',
    titleAr: 'مخطط المستقبل',
    description: 'Future tense planning game',
    descriptionAr: 'لعبة تخطيط المستقبل',
    difficulty: 'intermediate',
    category: 'Grammar',
    prerequisites: ['lesson-20'],
    estimatedTime: 16,
    unlocked: false,
    completed: false
  },

  // Unit 3: Communication (10 lessons + 6 games)
  {
    id: 'lesson-21',
    type: 'lesson',
    number: 33,
    title: 'Asking Questions',
    titleAr: 'طرح الأسئلة',
    description: 'Question formation and types',
    descriptionAr: 'تكوين الأسئلة والأنواع',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['game-12'],
    estimatedTime: 25,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-13',
    type: 'game',
    number: 34,
    title: 'Question Master Quiz',
    titleAr: 'اختبار سيد الأسئلة',
    description: 'Interactive question formation practice',
    descriptionAr: 'تدريب تكوين الأسئلة التفاعلي',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-21'],
    estimatedTime: 17,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-22',
    type: 'lesson',
    number: 35,
    title: 'Making Requests',
    titleAr: 'تقديم الطلبات',
    description: 'Polite requests and responses',
    descriptionAr: 'الطلبات المهذبة والردود',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['game-13'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-23',
    type: 'lesson',
    number: 36,
    title: 'Expressing Opinions',
    titleAr: 'التعبير عن الآراء',
    description: 'Opinion expressions and agreement',
    descriptionAr: 'تعبيرات الرأي والاتفاق',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-22'],
    estimatedTime: 22,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-14',
    type: 'game',
    number: 37,
    title: 'Opinion Debate Arena',
    titleAr: 'ساحة نقاش الآراء',
    description: 'Practice expressing and defending opinions',
    descriptionAr: 'تدرب على التعبير عن الآراء والدفاع عنها',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-23'],
    estimatedTime: 19,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-24',
    type: 'lesson',
    number: 38,
    title: 'Describing People',
    titleAr: 'وصف الأشخاص',
    description: 'Physical and personality descriptions',
    descriptionAr: 'الوصف الجسدي والشخصية',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['game-14'],
    estimatedTime: 21,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-25',
    type: 'lesson',
    number: 39,
    title: 'Describing Places',
    titleAr: 'وصف الأماكن',
    description: 'Location and environment descriptions',
    descriptionAr: 'وصف الموقع والبيئة',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-24'],
    estimatedTime: 19,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-15',
    type: 'game',
    number: 40,
    title: 'Description Detective',
    titleAr: 'محقق الوصف',
    description: 'Guess places and people from descriptions',
    descriptionAr: 'خمن الأماكن والأشخاص من الوصف',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-25'],
    estimatedTime: 15,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-26',
    type: 'lesson',
    number: 41,
    title: 'Telephone Conversations',
    titleAr: 'المحادثات الهاتفية',
    description: 'Phone etiquette and expressions',
    descriptionAr: 'آداب الهاتف والتعبيرات',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['game-15'],
    estimatedTime: 23,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-27',
    type: 'lesson',
    number: 42,
    title: 'At the Restaurant',
    titleAr: 'في المطعم',
    description: 'Restaurant conversations and ordering',
    descriptionAr: 'محادثات المطعم والطلب',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-26'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-28',
    type: 'lesson',
    number: 43,
    title: 'At the Hotel',
    titleAr: 'في الفندق',
    description: 'Hotel check-in and services',
    descriptionAr: 'تسجيل الوصول وخدمات الفندق',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-27'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-16',
    type: 'game',
    number: 44,
    title: 'Hotel Manager Simulator',
    titleAr: 'محاكي مدير الفندق',
    description: 'Handle hotel situations and conversations',
    descriptionAr: 'تعامل مع مواقف ومحادثات الفندق',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-28'],
    estimatedTime: 22,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-29',
    type: 'lesson',
    number: 45,
    title: 'Medical Situations',
    titleAr: 'المواقف الطبية',
    description: 'Health vocabulary and doctor visits',
    descriptionAr: 'مفردات الصحة وزيارات الطبيب',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['game-16'],
    estimatedTime: 24,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-30',
    type: 'lesson',
    number: 46,
    title: 'Emergency Situations',
    titleAr: 'حالات الطوارئ',
    description: 'Emergency vocabulary and responses',
    descriptionAr: 'مفردات الطوارئ والاستجابات',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-29'],
    estimatedTime: 21,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-17',
    type: 'game',
    number: 47,
    title: 'Emergency Response Trainer',
    titleAr: 'مدرب الاستجابة للطوارئ',
    description: 'Practice emergency communication',
    descriptionAr: 'تدرب على التواصل في الطوارئ',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['lesson-30'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-18',
    type: 'game',
    number: 48,
    title: 'Conversation Marathon',
    titleAr: 'ماراثون المحادثة',
    description: 'Extended conversation practice across scenarios',
    descriptionAr: 'تدريب محادثة ممتد عبر السيناريوهات',
    difficulty: 'intermediate',
    category: 'Communication',
    prerequisites: ['game-17'],
    estimatedTime: 25,
    unlocked: false,
    completed: false
  },

  // Unit 4: Grammar Expansion (10 lessons + 6 games)
  {
    id: 'lesson-31',
    type: 'lesson',
    number: 49,
    title: 'Present Continuous',
    titleAr: 'المضارع المستمر',
    description: 'Ongoing actions and present continuous usage',
    descriptionAr: 'الأعمال المستمرة واستخدام المضارع المستمر',
    difficulty: 'intermediate',
    category: 'Advanced Grammar',
    prerequisites: ['game-18'],
    estimatedTime: 26,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-19',
    type: 'game',
    number: 50,
    title: 'Action Detective',
    titleAr: 'محقق الأعمال',
    description: 'Identify ongoing actions in scenes',
    descriptionAr: 'حدد الأعمال المستمرة في المشاهد',
    difficulty: 'intermediate',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-31'],
    estimatedTime: 16,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-32',
    type: 'lesson',
    number: 51,
    title: 'Past Continuous',
    titleAr: 'الماضي المستمر',
    description: 'Past ongoing actions and interruptions',
    descriptionAr: 'الأعمال المستمرة في الماضي والانقطاعات',
    difficulty: 'intermediate',
    category: 'Advanced Grammar',
    prerequisites: ['game-19'],
    estimatedTime: 25,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-33',
    type: 'lesson',
    number: 52,
    title: 'Present Perfect',
    titleAr: 'المضارع التام',
    description: 'Present perfect tense and its applications',
    descriptionAr: 'المضارع التام وتطبيقاته',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-32'],
    estimatedTime: 28,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-20',
    type: 'game',
    number: 53,
    title: 'Perfect Tense Adventure',
    titleAr: 'مغامرة الأزمنة التامة',
    description: 'Master perfect tenses through storytelling',
    descriptionAr: 'أتقن الأزمنة التامة من خلال السرد',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-33'],
    estimatedTime: 20,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-34',
    type: 'lesson',
    number: 54,
    title: 'Past Perfect',
    titleAr: 'الماضي التام',
    description: 'Past perfect for earlier past actions',
    descriptionAr: 'الماضي التام للأعمال السابقة في الماضي',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['game-20'],
    estimatedTime: 27,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-35',
    type: 'lesson',
    number: 55,
    title: 'Modal Verbs (can, could, may)',
    titleAr: 'الأفعال المساعدة',
    description: 'Modal verbs for ability, possibility, permission',
    descriptionAr: 'الأفعال المساعدة للقدرة والإمكانية والإذن',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-34'],
    estimatedTime: 30,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-21',
    type: 'game',
    number: 56,
    title: 'Modal Verb Challenge',
    titleAr: 'تحدي الأفعال المساعدة',
    description: 'Practice modal verbs in context',
    descriptionAr: 'تدرب على الأفعال المساعدة في السياق',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-35'],
    estimatedTime: 18,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-36',
    type: 'lesson',
    number: 57,
    title: 'Conditional Sentences',
    titleAr: 'الجمل الشرطية',
    description: 'If-clauses and conditional structures',
    descriptionAr: 'جمل إذا والتراكيب الشرطية',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['game-21'],
    estimatedTime: 32,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-37',
    type: 'lesson',
    number: 58,
    title: 'Passive Voice',
    titleAr: 'المبني للمجهول',
    description: 'Passive voice formation and usage',
    descriptionAr: 'تكوين واستخدام المبني للمجهول',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-36'],
    estimatedTime: 29,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-22',
    type: 'game',
    number: 59,
    title: 'Voice Transformer',
    titleAr: 'محول الصوت',
    description: 'Transform between active and passive voice',
    descriptionAr: 'حول بين المبني للمعلوم والمجهول',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-37'],
    estimatedTime: 17,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-38',
    type: 'lesson',
    number: 60,
    title: 'Reported Speech',
    titleAr: 'الكلام المنقول',
    description: 'Direct and indirect speech conversion',
    descriptionAr: 'تحويل الكلام المباشر وغير المباشر',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['game-22'],
    estimatedTime: 31,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-39',
    type: 'lesson',
    number: 61,
    title: 'Relative Clauses',
    titleAr: 'الجمل الوصلية',
    description: 'Who, which, that, where clauses',
    descriptionAr: 'جمل من، التي، ذلك، حيث',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-38'],
    estimatedTime: 28,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-23',
    type: 'game',
    number: 62,
    title: 'Clause Connection Master',
    titleAr: 'سيد ربط الجمل',
    description: 'Connect sentences with relative clauses',
    descriptionAr: 'اربط الجمل بالجمل الوصلية',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-39'],
    estimatedTime: 19,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-40',
    type: 'lesson',
    number: 63,
    title: 'Comparison and Superlatives',
    titleAr: 'المقارنة والتفضيل',
    description: 'Comparative and superlative forms',
    descriptionAr: 'أشكال المقارنة والتفضيل',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['game-23'],
    estimatedTime: 26,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-24',
    type: 'game',
    number: 64,
    title: 'Comparison Arena',
    titleAr: 'ساحة المقارنة',
    description: 'Compare objects and make superlatives',
    descriptionAr: 'قارن الأشياء واصنع التفضيلات',
    difficulty: 'advanced',
    category: 'Advanced Grammar',
    prerequisites: ['lesson-40'],
    estimatedTime: 16,
    unlocked: false,
    completed: false
  },

  // Unit 5: Advanced Communication (10 lessons + 5 games)
  {
    id: 'lesson-41',
    type: 'lesson',
    number: 65,
    title: 'Business English',
    titleAr: 'الإنجليزية التجارية',
    description: 'Professional communication and business vocabulary',
    descriptionAr: 'التواصل المهني والمفردات التجارية',
    difficulty: 'advanced',
    category: 'Professional',
    prerequisites: ['game-24'],
    estimatedTime: 35,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-25',
    type: 'game',
    number: 66,
    title: 'Business Meeting Simulator',
    titleAr: 'محاكي اجتماع العمل',
    description: 'Practice professional meeting scenarios',
    descriptionAr: 'تدرب على سيناريوهات الاجتماعات المهنية',
    difficulty: 'advanced',
    category: 'Professional',
    prerequisites: ['lesson-41'],
    estimatedTime: 25,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-42',
    type: 'lesson',
    number: 67,
    title: 'Job Interviews',
    titleAr: 'مقابلات العمل',
    description: 'Interview skills and common questions',
    descriptionAr: 'مهارات المقابلة والأسئلة الشائعة',
    difficulty: 'advanced',
    category: 'Professional',
    prerequisites: ['game-25'],
    estimatedTime: 33,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-43',
    type: 'lesson',
    number: 68,
    title: 'Academic English',
    titleAr: 'الإنجليزية الأكاديمية',
    description: 'Academic writing and formal language',
    descriptionAr: 'الكتابة الأكاديمية واللغة الرسمية',
    difficulty: 'advanced',
    category: 'Academic',
    prerequisites: ['lesson-42'],
    estimatedTime: 38,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-26',
    type: 'game',
    number: 69,
    title: 'Academic Paper Builder',
    titleAr: 'بناء الورقة الأكاديمية',
    description: 'Structure academic writing step by step',
    descriptionAr: 'بنية الكتابة الأكاديمية خطوة بخطوة',
    difficulty: 'advanced',
    category: 'Academic',
    prerequisites: ['lesson-43'],
    estimatedTime: 30,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-44',
    type: 'lesson',
    number: 70,
    title: 'Presentation Skills',
    titleAr: 'مهارات العرض',
    description: 'Public speaking and presentation techniques',
    descriptionAr: 'التحدث أمام الجمهور وتقنيات العرض',
    difficulty: 'advanced',
    category: 'Professional',
    prerequisites: ['game-26'],
    estimatedTime: 36,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-45',
    type: 'lesson',
    number: 71,
    title: 'Negotiation Language',
    titleAr: 'لغة التفاوض',
    description: 'Negotiation strategies and language',
    descriptionAr: 'استراتيجيات التفاوض واللغة',
    difficulty: 'advanced',
    category: 'Professional',
    prerequisites: ['lesson-44'],
    estimatedTime: 34,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-27',
    type: 'game',
    number: 72,
    title: 'Negotiation Challenge',
    titleAr: 'تحدي التفاوض',
    description: 'Practice negotiation in various scenarios',
    descriptionAr: 'تدرب على التفاوض في سيناريوهات مختلفة',
    difficulty: 'advanced',
    category: 'Professional',
    prerequisites: ['lesson-45'],
    estimatedTime: 28,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-46',
    type: 'lesson',
    number: 73,
    title: 'Cultural Differences',
    titleAr: 'الاختلافات الثقافية',
    description: 'Cross-cultural communication',
    descriptionAr: 'التواصل عبر الثقافات',
    difficulty: 'advanced',
    category: 'Cultural',
    prerequisites: ['game-27'],
    estimatedTime: 32,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-47',
    type: 'lesson',
    number: 74,
    title: 'Technology and Internet',
    titleAr: 'التكنولوجيا والإنترنت',
    description: 'Modern technology vocabulary',
    descriptionAr: 'مفردات التكنولوجيا الحديثة',
    difficulty: 'advanced',
    category: 'Modern Topics',
    prerequisites: ['lesson-46'],
    estimatedTime: 29,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-48',
    type: 'lesson',
    number: 75,
    title: 'Environmental Issues',
    titleAr: 'القضايا البيئية',
    description: 'Environmental vocabulary and discussions',
    descriptionAr: 'مفردات البيئة والمناقشات',
    difficulty: 'advanced',
    category: 'Modern Topics',
    prerequisites: ['lesson-47'],
    estimatedTime: 31,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-28',
    type: 'game',
    number: 76,
    title: 'Environmental Debate',
    titleAr: 'نقاش البيئة',
    description: 'Debate environmental issues in English',
    descriptionAr: 'ناقش القضايا البيئية بالإنجليزية',
    difficulty: 'advanced',
    category: 'Modern Topics',
    prerequisites: ['lesson-48'],
    estimatedTime: 24,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-49',
    type: 'lesson',
    number: 77,
    title: 'Travel and Tourism',
    titleAr: 'السفر والسياحة',
    description: 'Travel planning and tourism vocabulary',
    descriptionAr: 'تخطيط السفر ومفردات السياحة',
    difficulty: 'advanced',
    category: 'Practical',
    prerequisites: ['game-28'],
    estimatedTime: 27,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-50',
    type: 'lesson',
    number: 78,
    title: 'Entertainment and Media',
    titleAr: 'الترفيه والإعلام',
    description: 'Media, entertainment, and arts vocabulary',
    descriptionAr: 'مفردات الإعلام والترفيه والفنون',
    difficulty: 'advanced',
    category: 'Cultural',
    prerequisites: ['lesson-49'],
    estimatedTime: 28,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-29',
    type: 'game',
    number: 79,
    title: 'Media Producer Simulator',
    titleAr: 'محاكي منتج الإعلام',
    description: 'Create and discuss media content',
    descriptionAr: 'أنشئ وناقش المحتوى الإعلامي',
    difficulty: 'advanced',
    category: 'Cultural',
    prerequisites: ['lesson-50'],
    estimatedTime: 26,
    unlocked: false,
    completed: false
  },

  // Unit 6: Mastery Level (6 lessons + 6 games)
  {
    id: 'lesson-51',
    type: 'lesson',
    number: 80,
    title: 'Advanced Grammar Review',
    titleAr: 'مراجعة القواعد المتقدمة',
    description: 'Comprehensive grammar review and integration',
    descriptionAr: 'مراجعة شاملة للقواعد والتكامل',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['game-29'],
    estimatedTime: 40,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-30',
    type: 'game',
    number: 81,
    title: 'Grammar Master Tournament',
    titleAr: 'بطولة سيد القواعد',
    description: 'Ultimate grammar challenge tournament',
    descriptionAr: 'بطولة تحدي القواعد النهائية',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['lesson-51'],
    estimatedTime: 35,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-52',
    type: 'lesson',
    number: 82,
    title: 'Idiomatic Expressions',
    titleAr: 'التعابير الاصطلاحية',
    description: 'Common idioms and expressions',
    descriptionAr: 'التعابير الاصطلاحية والعبارات الشائعة',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['game-30'],
    estimatedTime: 37,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-31',
    type: 'game',
    number: 83,
    title: 'Idiom Detective',
    titleAr: 'محقق التعابير',
    description: 'Solve puzzles using idiomatic expressions',
    descriptionAr: 'حل الألغاز باستخدام التعابير الاصطلاحية',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['lesson-52'],
    estimatedTime: 22,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-53',
    type: 'lesson',
    number: 84,
    title: 'Academic Writing',
    titleAr: 'الكتابة الأكاديمية',
    description: 'Advanced academic writing techniques',
    descriptionAr: 'تقنيات الكتابة الأكاديمية المتقدمة',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['game-31'],
    estimatedTime: 42,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-54',
    type: 'lesson',
    number: 85,
    title: 'Professional Communication',
    titleAr: 'التواصل المهني',
    description: 'Advanced professional communication skills',
    descriptionAr: 'مهارات التواصل المهني المتقدمة',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['lesson-53'],
    estimatedTime: 39,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-32',
    type: 'game',
    number: 86,
    title: 'Professional Challenge Suite',
    titleAr: 'مجموعة التحدي المهني',
    description: 'Complete professional scenarios challenge',
    descriptionAr: 'تحدي السيناريوهات المهنية الكامل',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['lesson-54'],
    estimatedTime: 45,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-55',
    type: 'lesson',
    number: 87,
    title: 'Advanced Listening Skills',
    titleAr: 'مهارات الاستماع المتقدمة',
    description: 'Complex listening comprehension and analysis',
    descriptionAr: 'فهم الاستماع المعقد والتحليل',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['game-32'],
    estimatedTime: 36,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-33',
    type: 'game',
    number: 88,
    title: 'Listening Master Challenge',
    titleAr: 'تحدي سيد الاستماع',
    description: 'Advanced listening comprehension tests',
    descriptionAr: 'اختبارات فهم الاستماع المتقدمة',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['lesson-55'],
    estimatedTime: 30,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-34',
    type: 'game',
    number: 89,
    title: 'Fluency Olympics',
    titleAr: 'أولمبياد الطلاقة',
    description: 'Ultimate fluency test across all skills',
    descriptionAr: 'اختبار الطلاقة النهائي عبر جميع المهارات',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['game-33'],
    estimatedTime: 50,
    unlocked: false,
    completed: false
  },
  {
    id: 'game-35',
    type: 'game',
    number: 90,
    title: 'English Master Certification',
    titleAr: 'شهادة سيد الإنجليزية',
    description: 'Final comprehensive mastery assessment',
    descriptionAr: 'التقييم الشامل النهائي للإتقان',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['game-34'],
    estimatedTime: 60,
    unlocked: false,
    completed: false
  },
  {
    id: 'lesson-56',
    type: 'lesson',
    number: 91,
    title: 'Final Assessment and Certification',
    titleAr: 'التقييم النهائي والشهادة',
    description: 'Complete your English learning journey',
    descriptionAr: 'أكمل رحلة تعلم الإنجليزية',
    difficulty: 'advanced',
    category: 'Mastery',
    prerequisites: ['game-35'],
    estimatedTime: 45,
    unlocked: false,
    completed: false
  }
];

// Game configurations for each game type
export const GAME_CONFIGURATIONS: Record<string, GameConfig> = {
  'game-1': { gameType: 'memory-cards', difficulty: 'easy', topics: ['alphabet', 'letters'] },
  'game-2': { gameType: 'vocabulary-matching', difficulty: 'easy', topics: ['numbers'], timeLimit: 300 },
  'game-3': { gameType: 'image-quiz', difficulty: 'easy', topics: ['colors'] },
  'game-4': { gameType: 'conversation-simulator', difficulty: 'easy', topics: ['greetings'] },
  'game-5': { gameType: 'grammar-adventure', difficulty: 'easy', topics: ['present-simple'] },
  'game-6': { gameType: 'word-puzzle', difficulty: 'easy', topics: ['family'] },
  'game-7': { gameType: 'image-quiz', difficulty: 'easy', topics: ['body-parts'] },
  'game-8': { gameType: 'pronunciation-practice', difficulty: 'easy', topics: ['time'] },
  'game-9': { gameType: 'conversation-simulator', difficulty: 'easy', topics: ['food', 'restaurant'] },
  'game-10': { gameType: 'vocabulary-matching', difficulty: 'easy', topics: ['transportation'] },
  'game-11': { gameType: 'grammar-adventure', difficulty: 'medium', topics: ['past-simple'] },
  'game-12': { gameType: 'story-builder', difficulty: 'medium', topics: ['future-tense'] },
  'game-13': { gameType: 'spelling-challenge', difficulty: 'medium', topics: ['questions'] },
  'game-14': { gameType: 'conversation-simulator', difficulty: 'medium', topics: ['opinions'] },
  'game-15': { gameType: 'word-puzzle', difficulty: 'medium', topics: ['descriptions'] },
  'game-16': { gameType: 'conversation-simulator', difficulty: 'medium', topics: ['hotel'] },
  'game-17': { gameType: 'listening-comprehension', difficulty: 'medium', topics: ['emergency'] },
  'game-18': { gameType: 'conversation-simulator', difficulty: 'medium', topics: ['general'] },
  'game-19': { gameType: 'image-quiz', difficulty: 'medium', topics: ['present-continuous'] },
  'game-20': { gameType: 'grammar-adventure', difficulty: 'hard', topics: ['perfect-tenses'] },
  'game-21': { gameType: 'vocabulary-matching', difficulty: 'hard', topics: ['modal-verbs'] },
  'game-22': { gameType: 'grammar-adventure', difficulty: 'hard', topics: ['passive-voice'] },
  'game-23': { gameType: 'word-puzzle', difficulty: 'hard', topics: ['relative-clauses'] },
  'game-24': { gameType: 'spelling-challenge', difficulty: 'hard', topics: ['comparatives'] },
  'game-25': { gameType: 'conversation-simulator', difficulty: 'hard', topics: ['business'] },
  'game-26': { gameType: 'story-builder', difficulty: 'hard', topics: ['academic'] },
  'game-27': { gameType: 'conversation-simulator', difficulty: 'hard', topics: ['negotiation'] },
  'game-28': { gameType: 'listening-comprehension', difficulty: 'hard', topics: ['environment'] },
  'game-29': { gameType: 'story-builder', difficulty: 'hard', topics: ['media'] },
  'game-30': { gameType: 'grammar-adventure', difficulty: 'hard', topics: ['all-grammar'] },
  'game-31': { gameType: 'word-puzzle', difficulty: 'hard', topics: ['idioms'] },
  'game-32': { gameType: 'conversation-simulator', difficulty: 'hard', topics: ['professional'] },
  'game-33': { gameType: 'listening-comprehension', difficulty: 'hard', topics: ['advanced'] },
  'game-34': { gameType: 'pronunciation-practice', difficulty: 'hard', topics: ['fluency'] },
  'game-35': { gameType: 'grammar-adventure', difficulty: 'hard', topics: ['mastery'], timeLimit: 3600 }
};

// Lesson configurations for dynamic lesson generation
export const LESSON_CONFIGURATIONS: Record<string, LessonConfig> = {
  'lesson-1': { 
    topic: 'Introduction to English Language',
    objectives: ['Understand English alphabet', 'Learn basic sounds', 'Recognize English structure'],
    vocabulary: ['English', 'language', 'learn', 'speak', 'understand'],
    grammarPoints: ['Basic sentence structure', 'Subject-verb relationship'],
    examples: 20
  },
  'lesson-2': {
    topic: 'English Alphabet',
    objectives: ['Master all 26 letters', 'Practice pronunciation', 'Recognize letter shapes'],
    vocabulary: ['letter', 'alphabet', 'vowel', 'consonant', 'pronunciation'],
    grammarPoints: ['Letter naming', 'Phonetic sounds'],
    examples: 20
  },
  // Add more lesson configurations as needed...
};
